title: EKH Code Reviews
longtitle: Code Reviews at Lund's Economic History Department

remote_theme: just-the-docs/just-the-docs
toc:
    enabled: true
    h_min: 1
    h_max: 3

exclude: code/
include: _pages